name: Ruby Unit Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'         # ignore all tag pushes
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
          #triplestore: [ 'fs', 'ag', 'vo', 'gd' ]
         triplestore: [ 'fs', 'ag' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Install system dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y raptor2-utils
    # - name: Set up Java 11
    #   uses: actions/setup-java@v5
    #   with:
    #     distribution: temurin
    #     java-version: '11'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: create config.rb file
      run: cp config/config.test.rb config/config.rb
    - name: Run unit tests
      run: |
        test:docker:${{ matrix.triplestore }}:linux TESTOPTS="-v"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        verbose: true
        fail_ci_if_error: false # optional (default = false)
