name: Ruby Unit Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'         # ignore all tag pushes
  pull_request:

jobs:
  test:
    env:
      COMPOSE_CMD: >
        docker compose -f docker-compose.yml
        -f dev/compose/linux/${{ matrix.triplestore }}.yml
        --profile linux
        --profile ${{ matrix.triplestore }}
    strategy:
      fail-fast: false
      matrix:
          #triplestore: [ 'fs', 'ag', 'vo', 'gd' ]
         triplestore: [ 'fs', 'ag' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: create config.rb file
      run: cp config/config.test.rb config/config.rb
    - name: Build docker container
      run: >
        $COMPOSE_CMD build
    - name: Run unit tests
      run: >
        $COMPOSE_CMD run -v "$PWD/coverage:/app/coverage" -e CI=true
        test-linux bundle exec rake test TESTOPTS="-v"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        verbose: true
        fail_ci_if_error: false # optional (default = false)
