name: Ruby Unit Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'         # ignore all tag pushes
  pull_request:

jobs:
  test:
    env:
      RUBY_VERSION: '3.2'
      COMPOSE_CMD: >
        docker compose -f docker-compose.yml
        -f dev/compose/linux/docker-compose.ci.yml
        -f dev/compose/linux/${{ matrix.triplestore }}.yml
        --profile linux
        --profile ${{ matrix.triplestore }}
    strategy:
      fail-fast: false
      matrix:
          #triplestore: [ 'fs', 'ag', 'vo', 'gd' ]
         triplestore: [ 'fs', 'ag' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: create config.rb file
      run: cp config/config.test.rb config/config.rb
    - name: Build test image with cache
      uses: docker/bake-action@v6
      with:
        files: |
          docker-compose.yml
          dev/compose/linux/docker-compose.ci.yml
          dev/compose/linux/${{ matrix.triplestore }}.yml
        targets: test-linux
        set: |
          test-linux.args.RUBY_VERSION=${{ env.RUBY_VERSION }}
          test-linux.cache-from=type=gha,scope=test-linux-ruby-${{ env.RUBY_VERSION }}
          test-linux.cache-to=type=gha,mode=max,scope=test-linux-ruby-${{ env.RUBY_VERSION }}
          test-linux.output=type=docker
          test-linux.tags=ontologies_linked_data-test-linux:ci
    - name: Run unit tests
      run: >
        $COMPOSE_CMD run --no-build -v "$PWD/coverage:/app/coverage" -e CI=true
        test-linux bundle exec rake test TESTOPTS="-v"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        verbose: true
        fail_ci_if_error: false # optional (default = false)
